-- PrajaMitra Seed Data Migration V2
-- Seeds standard Andhra Pradesh Government service categories, citizen services, and demo records

-- 1. Insert Service Categories
INSERT INTO service_categories (id, name, name_te, description) VALUES
(1, 'revenue_land', 'రెవెన్యూ & భూమి', 'అడంగల్, 1-B, మ్యుటేషన్, కుల/ఆదాయ ధృవీకరణ, F-లైన్ సర్వే'),
(2, 'registration_stamps', 'రిజిస్ట్రేషన్ & స్టాంపులు', 'ఆస్తి నమోదు, ఈసీ (EC), మార్కెట్ విలువ, స్లాట్ బుకింగ్'),
(3, 'panchayat_raj', 'పంచాయతీ రాజ్ & గ్రామీణ', 'ఇంటి పన్ను, PTIN, లేఅవుట్ అనుమతులు, జనన/మరణ రికార్డులు'),
(4, 'civil_supplies', 'పౌర సరఫరాలు (రేషన్)', 'రైస్ కార్డు, సభ్యుల చేర్పు/తొలగింపు, రేషన్ డీలర్ సేవలు'),
(5, 'social_welfare', 'సంక్షేమ పథకాలు', 'NTR భరోసా పింఛన్లు, చేయూత, కళ్యాణమస్తు, ఉపకారవేతనాలు'),
(6, 'school_education', 'పాఠశాల విద్య', 'తల్లికి వందనం, జగనన్న విద్యా కానుక, బదిలీ సర్టిఫికెట్లు'),
(7, 'agriculture', 'వ్యవసాయం & అనుబంధ', 'అన్నదాత సుఖీభవ (రైతు భరోసా), ఈ-క్రాప్ నమోదు, విత్తన పంపిణీ'),
(8, 'health', 'వైద్యం & ఆరోగ్యం', 'ఆరోగ్యశ్రీ ఈ-కార్డు, ఉచిత చికిత్స, PHC సేవలు, తల్లి బిడ్డ సంరక్షణ'),
(9, 'municipal', 'పురపాలక సేవలు', 'ట్రేడ్ లైసెన్స్, నల్లా కనెక్షన్, మ్యుటేషన్, బిల్డింగ్ ప్లాన్'),
(10, 'transport', 'రవాణా & డ్రైవింగ్', 'LLR లెర్నర్స్ లైసెన్స్, డ్రైవింగ్ లైసెన్స్, RC బదిలీ'),
(11, 'police', 'పోలీస్ & భద్రత', 'పోలీస్ క్లియరెన్స్, ఈ-చలానా, పోయిన పత్రాల రిపోర్ట్, దిశ యాప్'),
(12, 'energy', 'విద్యుత్ (APSPDCL/EPDCL)', 'కొత్త విద్యుత్ సర్వీస్, పేరు మార్పు, కేటగిరీ మార్పు, బిల్లు చెల్లింపు')
ON CONFLICT (id) DO NOTHING;

-- Reset sequence for categories
SELECT setval('service_categories_id_seq', (SELECT MAX(id) FROM service_categories));

-- 2. Insert Services
INSERT INTO services (id, category_id, service_code, name, name_te, description, description_te, eligibility, documents, process, fees, timeline, official_url, source, verified) VALUES
(1, 1, 'AP-REV-LD-001', 
 'Webland Adangal and Pahani Record Viewing', 
 'వెబ్‌ల్యాండ్ అడంగల్ మరియు పహాణీ రికార్డు పరిశీలన', 
 'Online facility to view land details, ownership, crop pattern and land classification in Andhra Pradesh.', 
 'ఆంధ్రప్రదేశ్ భూ రికార్డుల సమాచారాన్ని (అడంగల్/పహాణీ) వెబ్‌ల్యాండ్ ఆన్‌లైన్ ద్వారా తెలుసుకొనే సౌకర్యం.', 
 'Any landowner who possesses agricultural or other land holdings in AP.', 
 'Pattadar Aadhaar number, Khata number, or Survey number.', 
 'Select District, Mandal, Village on Meebhoomi portal, enter Survey or Khata number to view/download Adangal.', 
 'Online viewing is Free. Certified printed copy at MeeSeva is ₹25.', 
 'Instantaneous (Online)', 
 'https://meebhoomi.ap.gov.in/', 
 'MeeBhoomi Portal / CCLA AP',
 true),

(2, 2, 'AP-REG-002', 
 'Encumbrance Certificate (EC) Issuance', 
 'విక్రయ విక్రయేతర ఆస్తి ధృవీకరణ పత్రం (EC)', 
 'Check previous transaction history, registered deeds, and legal claims on a property.', 
 'ఆస్తిపై ఎటువంటి లోన్లు లేదా మునుపటి రిజిస్ట్రేషన్లు ఉన్నాయో తెలుసుకోవడానికి ఈసీ అత్యవసరం.', 
 'Property buyers or owners in Andhra Pradesh.', 
 'Property document number, registration year, SRO location, owner name.', 
 'Submit property bounds, survey number or registration doc number on registration portal.', 
 'Online search is Free. Certified copy is ₹220.', 
 'Instantaneous online download; 3 days for certified signed copy.', 
 'https://registration.ap.gov.in/', 
 'IGRS Andhra Pradesh',
 true),

(3, 1, 'AP-REV-MUT-003', 
 'ROR 1-B Mutation and Title Deed Transfer', 
 'ROR 1-B టైటిల్ డీడ్ బదిలీ మరియు మ్యుటేషన్', 
 'Transfer of Pattadar Passbook and Revenue Record of Rights (ROR 1-B) upon sale, gift, or inheritance.', 
 'భూమి కొనుగోలు, బహుమతి లేదా వారసత్వం ద్వారా పొందిన హక్కుల ప్రకారం పట్టాదారు పాస్ పుస్తకం మరియు రికార్డుల్లో పేరు నమోదు.', 
 'Land purchaser or legal heir with valid registered deed.', 
 'Registered Sale Deed / Gift Deed, Death Certificate (for inheritance), Family Member Certificate, Pattadar Passbook, Aadhaar Card.', 
 'Submit application at Grama Sachivalayam / MeeSeva. VRO inspects and Tahsildar approves ROR 1-B issuance.', 
 'User charge ₹35 + Statutory mutation fee.', 
 '15 working days', 
 'https://meebhoomi.ap.gov.in/', 
 'Revenue (CCLA) & MeeSeva',
 true),

(4, 1, 'AP-REV-CERT-004', 
 'Integrated Caste and Income Certificate', 
 'కుల మరియు ఆదాయ ధృవీకరణ పత్రం', 
 'Official government certificate for SC, ST, BC and EWS category validation along with family annual income.', 
 'విద్యా ప్రవేశాలు, ప్రభుత్వ ఉద్యోగాలు మరియు సంక్షేమ పథకాల కొరకు అవసరమైన అధికారిక ధృవీకరణ పత్రం.', 
 'Permanent residents of Andhra Pradesh belonging to respective communities.', 
 'Aadhaar card, Ration card / Rice card, previous caste certificate copy or school TC, salary certificate / land holding proof.', 
 'Apply via Village Sachivalayam / MeeSeva. Digital certificate issued with digital signature of Tahsildar.', 
 '₹35 application fee', 
 '7 to 14 working days', 
 'https://onlineap.meeseva.gov.in/', 
 'MeeSeva Online Portal',
 true),

(5, 4, 'AP-CS-RICE-005', 
 'New Rice Card Application & Member Addition', 
 'కొత్త రైస్ కార్డు దరఖాస్తు మరియు సభ్యుల చేర్పు', 
 'Public Distribution System (PDS) Rice Card issuance and addition of family members or newborns.', 
 'రేషన్ సరుకులు మరియు ప్రభుత్వ పథకాల కొరకు కొత్త రైస్ కార్డు దరఖాస్తు లేదా కుటుంబంలో కొత్త సభ్యులను చేర్చడం.', 
 'Families with annual income below ₹1,20,000 (rural) or ₹1,44,000 (urban), non-tax payers, holding less than specified land limit.', 
 'Aadhaar cards of all family members, Birth Certificate (for newborns), Marriage Certificate (for newlywed spouses), Electricity bill.', 
 'Apply at local Grama/Ward Sachivalayam. Field verification done by Welfare Assistant within 7 days.', 
 'Free of cost', 
 '10 working days', 
 'https://epdsap.ap.gov.in/', 
 'Civil Supplies (EPDS AP)',
 true),

(6, 7, 'AP-AGRI-RYTHU-006', 
 'Annadata Sukhibhava / Rythu Bharosa Scheme', 
 'అన్నదాత సుఖీభవ (రైతు భరోసా) రైతు సహాయం', 
 'Direct input financial assistance of ₹20,000 per year per farmer family in Andhra Pradesh.', 
 'రైతు కుటుంబాలకు పంట పెట్టుబడి కొరకు సంవత్సరానికి ₹20,000 రూపాయల ప్రత్యక్ష ఆర్థిక సహాయ పథకం.', 
 'Small and marginal farmers holding cultivable agricultural land, and enrolled Tenant Farmers.', 
 'Aadhaar card, 1-B Pattadar passbook / CCRC (Tenant Farmer Card), Active bank account linked with Aadhaar NPCI mapping.', 
 'Automatic inclusion through e-Crop booking and Land record synchronization at Rythu Seva Kendram (RSK).', 
 'Free of cost', 
 'Disbursed in seasonal tranches (Kharif / Rabi)', 
 'https://karshak.ap.gov.in/', 
 'Agriculture Department AP',
 true),

(7, 8, 'AP-HEALTH-AAROGYA-007', 
 'Dr. NTR Aarogyasri Health Card & Treatment', 
 'డా. ఎన్టీఆర్ ఆరోగ్యశ్రీ హెల్త్ కార్డు మరియు ఉచిత చికిత్స', 
 'Free cashless medical treatment up to ₹25 Lakhs per family per year in empanelled network hospitals.', 
 'నెట్‌వర్క్ ఆసుపత్రులలో కుటుంబానికి సంవత్సరానికి ₹25 లక్షల వరకు ఉచిత క్యాష్‌లెస్ వైద్య చికిత్స అందించే పథకం.', 
 'Rice Card holders, BPL families, or families with annual income under ₹5 Lakhs in Andhra Pradesh.', 
 'Aadhaar Card, Rice Card / Aarogyasri Card, Patient medical reports.', 
 'Visit any Aarogyasri network hospital. Aarogya Mithra desk validates identity and initiates cashless admission.', 
 '100% Free for eligible treatments', 
 'Instant pre-authorization at hospital', 
 'https://aarogyasri.ap.gov.in/', 
 'Dr. NTR Aarogyasri Trust',
 true),

(8, 6, 'AP-EDU-THALLI-008', 
 'Thalliki Vandanam Scheme (Mothers Support)', 
 'తల్లికి వందనం విద్యా ప్రోత్సాహక పథకం', 
 'Annual financial assistance of ₹15,000 per school-going child to mother for education support.', 
 'పాఠశాలకు వెళ్లే ప్రతి విద్యార్థి తల్లి బ్యాంకు ఖాతాలో ఏటా ₹15,000 జమ చేసే విద్యా ప్రోత్సాహక పథకం.', 
 'Mothers of students studying Classes 1 to 12 in recognized schools/junior colleges with 75% attendance.', 
 'Student Child Info ID, Mother Aadhaar, Student Aadhaar, Rice Card, Bank Passbook.', 
 'Enrolment handled directly through HM / Principal on Jnanabhumi / Student portal.', 
 'Free of cost', 
 'Annual academic disbursement', 
 'https://jnanabhumi.ap.gov.in/', 
 'Department of School Education AP',
 true),

(9, 3, 'AP-PR-PTIN-009', 
 'Gram Panchayat House Tax Assessment & PTIN', 
 'గ్రామ పంచాయతీ ఆస్తి/ఇంటి పన్ను అసెస్‌మెంట్ మరియు PTIN కేటాయింపు', 
 'Assessment of newly constructed residential/commercial buildings and issuance of Property Tax Identification Number (PTIN).', 
 'గ్రామాల్లో కొత్తగా నిర్మించిన ఇళ్లకు పన్ను నిర్ణయించి PTIN నంబర్ కేటాయించే పద్ధతి.', 
 'Building owners in Gram Panchayat areas.', 
 'Registered Document / Possession Certificate, Building approval plan, Electricity connection bill, Aadhaar Card.', 
 'Apply online or at Grama Sachivalayam. Panchayat Secretary inspects premises and enters assessment.', 
 'User charge ₹35 + Calculated house tax.', 
 '15 working days', 
 'https://panchayat.ap.gov.in/', 
 'Panchayat Raj & Rural Development',
 true),

(10, 10, 'AP-TRANS-LLR-010', 
 'Learner Driving Licence (LLR) & Driving Licence', 
 'లెర్నర్స్ డ్రైవింగ్ లైసెన్స్ (LLR) మరియు పర్మనెంట్ డ్రైవింగ్ లైసెన్స్', 
 'Online computer-based test slot booking and issuance of LLR and Permanent Driving Licence.', 
 'ఆన్‌లైన్ ద్వారా లెర్నర్స్ లైసెన్స్ టెస్ట్ బుకింగ్ మరియు డ్రైవింగ్ లైసెన్స్ పొందే విధానం.', 
 'Age 16+ for Gearless 2-wheeler; Age 18+ for Light Motor Vehicle (Car/Bike with gear).', 
 'Age proof (SSC certificate / Birth Certificate), Address proof (Aadhaar Card), Medical Certificate Form 1-A (for transport/above 40 yrs).', 
 'Apply on Sarathi Parivahan, pay fee, take online learner test from home or RTA office.', 
 '₹260 for LLR (Two-wheeler + LMV)', 
 'Instant LLR download on passing test', 
 'https://parivahan.gov.in/', 
 'Transport Department / Sarathi Parivahan',
 true),

(11, 2, 'AP-REG-MARKET-011', 
 'Land & Property Market Value Search', 
 'భూమి మరియు ఆస్తి రిజిస్ట్రేషన్ మార్కెట్ విలువ శోధన', 
 'Official government unit rate per square yard or acre for stamp duty and registration fee calculations.', 
 'ఆస్తి రిజిస్ట్రేషన్ స్టాంప్ డ్యూటీ గణన కొరకు ప్రభుత్వం నిర్దేశించిన మార్కెట్ రేట్ల పరిశీలన.', 
 'Public, property buyers, sellers, advocates and document writers.', 
 'District, Mandal, Village, Survey Number / Ward and Door Number.', 
 'Select District, Mandal, Village/Locality on Registration portal to view agricultural or non-agricultural market rates.', 
 'Free of cost', 
 'Instantaneous', 
 'https://registration.ap.gov.in/', 
 'IGRS Andhra Pradesh',
 true),

(12, 1, 'AP-REV-EWS-012', 
 'Economically Weaker Section (EWS) Certificate', 
 'ఈడబ్ల్యూఎస్ (EWS) ధృవీకరణ పత్రం', 
 '10% reservation eligibility certificate for general category citizens with family annual income under ₹8 Lakhs.', 
 'జనరల్ కేటగిరీ పేదలకు 10 శాతం రిజర్వేషన్ పొందేందుకు అవసరమైన EWS సర్టిఫికెట్.', 
 'General category citizens not covered under SC, ST, or BC reservations having annual income below ₹8 Lakhs.', 
 'Aadhaar Card, Income certificate / ITR returns, Land holding documents, Family declaration, Notarized affidavit.', 
 'Submit application at Grama/Ward Sachivalayam. Tahsildar verifies and approves.', 
 '₹35 application fee', 
 '15 working days', 
 'https://onlineap.meeseva.gov.in/', 
 'MeeSeva Online Portal',
 true)
ON CONFLICT (id) DO NOTHING;

-- Reset sequence for services
SELECT setval('services_id_seq', (SELECT MAX(id) FROM services));

